delete from vip_orders where userId>10000;
delete from wallets where userId>10000;
delete from tree_paths where ancestor>10000 ||  descendant>10000;
delete from tiktok_task_price_orders where   userId>10000;
delete from tiktok_task where   userId>10000;
delete from wallet_usd_logs  where   userId>10000;
delete from wallet_ttt_logs  where   userId>10000;
delete from freeze_proxy_logs where   userId>10000;
delete from evm_user_wallet where   uid>10000;
delete from trx_user_wallet where uid >10000;

delete from business_job;
delete from evm_token_recharge;
delete from evm_token_withdraw;
delete from fiat_recharge_order;
delete from fiat_withdraw_order;
delete from freeze_proxy_logs;
delete from news_user;
delete from news_en_us;
delete from news_in_id;
delete from news_th_th;
delete from news_vi_vn;
delete from news_zh_cn;
delete from news;
delete from  stat_balance;
delete from stat_input_and_output;
delete from stat_dynamic_and_static;
delete from stat_user;
delete from  sys_errorlog;
delete from  sys_loginlog;
delete from  sys_operationlog;
delete FROM tiktok_account;
delete from tiktok_task_price_orders;
delete from treat_guest_dinner;
delete from trx_token_recharge;
delete from trx_token_withdraw;
delete from update_user_level_job;
delete from vip_orders;
delete from wallets_usd_recharge;
delete from wallets_usd_withdraw;
delete from app_user_task;
delete from app_users where id >10000;
alter table app_users AUTO_INCREMENT = 10001;
